### ISSUE TITLE
URL token

### ISSUE THREAD

**Issue by justinmk** [neovim/tree-sitter-vimdoc#11]
Seems like the parser currently doesn't recognize URLs in text. The old [makehtml.awk](https://github.com/neovim/neovim/blob/52e4b779e3df1335efc4774e8dfc199d07e24bfd/runtime/doc/makehtml.awk#L325) script had primitive support for that, and it's useful for rendering URLs as hyperlinks.

Example text: https://github.com/neovim/neovim/blob/52e4b779e3df1335efc4774e8dfc199d07e24bfd/runtime/doc/api.txt#L20-L31

```
==============================================================================
API Usage                                               *api-rpc* *RPC* *rpc*

                                                        *msgpack-rpc*
RPC is the typical way to control Nvim programmatically.  Nvim implements the
MessagePack-RPC protocol:
  https://github.com/msgpack-rpc/msgpack-rpc/blob/master/spec.md
  https://github.com/msgpack/msgpack/blob/0b8f5ac/spec.md

Many clients use the API: user interfaces (GUIs), remote plugins, scripts like
"nvr" (https://github.com/mhinz/neovim-remote).  Even Nvim itself can control
other Nvim instances.  API clients can:

  - Call any API function
  - Listen for events
  - Receive remote calls from Nvim
```

**Comment by vigoux** [comment]
Sounds like something that is easy to do, I'll add that!

**Comment by justinmk** [comment]
@vigoux fwiw, i'm hacking on this, but also ended up removing `scanner.c` 👀  ... not sure if I'll succeed
