### ISSUE TITLE
License inconsistency between crate and LICENSE file

### ISSUE THREAD

**Issue by jamessan** [neovim/tree-sitter-vimdoc#112]
Cargo.toml states the crate is using the MIT license while LICENSE states Apache-2.0 is the project's license.  Is Cargo.toml just an oversight from the default `tree-sitter generate` output?

**Comment by clason** [comment]
Probably. @vigoux?

**Comment by vigoux** [comment]
I have absolutely no idea, I'd guess that the tree-sitter generate, extracts the license frol package.json, so it'd probably be good to look into that

**Comment by clason** [comment]
I mean, what is the intended license?

**Comment by vigoux** [comment]
I think I had it to Apache2 for compatibility with neovim's license.

**Comment by clason** [comment]
Ok, I'll fix the package files when I regenerate the parser with the upcoming tree-sitter version (and make a release).

**Comment by clason** [comment]
(The vimscript parser has an MIT license, btw.)

**Comment by clason** [comment]
@jamessan is this blocking you?

**Comment by jamessan** [comment]
No, just something I noticed while packaging for Debian.  For now I've documented both licenses.  If a future version unifies to one license, I'll update the Debian metadata.

**Comment by clason** [comment]
I just pushed a commit fixing the cargo toml. If it helps, I can make a new patch release.
