### ISSUE TITLE
Whitespace handling for table line items

### ISSUE THREAD

**Issue by muhmud** [neovim/tree-sitter-vimdoc#117]
Currently, a table like this:

![image](https://github.com/neovim/tree-sitter-vimdoc/assets/7550982/5ecd2219-1b3d-4298-9077-5cec2e368142)

gets rendered like this:

![image](https://github.com/neovim/tree-sitter-vimdoc/assets/7550982/c404d5cc-3768-41c2-811b-4a1c0948e692)

Data on the whitespace does not seem to appear in the parsed tree-sitter document in this case, though I do see it for `codeblock`. Is there something that can be done to handle this better?

**Comment by clason** [comment]
Nope, that's something that can't be done with a syntax tree, given the loose vimdoc format.

**Comment by clason** [comment]
(In 90% of cases, the issue is with the docs themselves; if they are meant to be a table, they should be marked up as such.)
