### ISSUE TITLE
`:help` docs look broken

### ISSUE THREAD

**Issue by AlexKurisu** [neovim/tree-sitter-vimdoc#128]
NVIM v0.10.0-dev-2590+g8955cef0c6.
`:help` docs look broken. `:help vim.diagnostic.Opts`, for example, looks like this:
![image](https://github.com/neovim/tree-sitter-vimdoc/assets/60626727/062e9fa1-5bef-4170-9b27-f217296b9cae)
This is not a colorscheme problem as nothing changes after switching to `:colorscheme default`

**Comment by justinmk** [comment]
Don't think this is related to the grammar (this repo), unless https://github.com/neovim/tree-sitter-vimdoc/pull/125 was already added to Nvim and caused a regression? @ObserverOfTime

**Comment by clason** [comment]
Can confirm @ObserverOfTime

**Comment by AlexKurisu** [comment]
> unless #125 was already added to Nvim and caused a regression

I use https://github.com/nvim-treesitter/nvim-treesitter and it is updated to commit 90a396267e117835c778bdbda6f7db86b601d829 there

**Comment by ObserverOfTime** [comment]
Works on my machine :thinking: 
![image](https://github.com/neovim/tree-sitter-vimdoc/assets/24971970/c5e08b1b-004e-4509-bdfc-71705b276485)

**Comment by ObserverOfTime** [comment]
If the parser works then it's likely an issue with the tooling. I'll update Neovim to HEAD and check.

**Comment by AlexKurisu** [comment]
> If the parser works then it's likely an issue with the tooling. I'll update Neovim to HEAD and check.

I have tree-sitter 0.22.1 if that matters

**Comment by ObserverOfTime** [comment]
Yep, worked on neovim/neovim@6d680d9 (last commit I'd built) but is broken on neovim/neovim@8955cef.
I believe this needs to be fixed in Neovim and there's nothing to be done here.

**Comment by clason** [comment]
@AlexKurisu can you try the latest commit?

**Comment by ObserverOfTime** [comment]
Ackshually, some docs have multiple modelines. :nerd_face:

**Comment by clason** [comment]
> Yep, worked on [neovim/neovim@6d680d9](https://github.com/neovim/neovim/commit/6d680d9) (last commit I'd built) but is broken on [neovim/neovim@8955cef](https://github.com/neovim/neovim/commit/8955cef). I believe this needs to be fixed in Neovim (likely just an update) and there's nothing to be done here.

Please bisect then. The last commit is unrelated.

**Comment by AlexKurisu** [comment]
> @AlexKurisu can you try the latest commit?

I don't know how :(

**Comment by clason** [comment]
Rather unsurprisingly, it's https://github.com/neovim/neovim/commit/cb46f6e467268edf917cc3617b4c024a66b256de

@gpanders

**Comment by ObserverOfTime** [comment]
> Rather unsurprisingly, it's [neovim/neovim@cb46f6e](https://github.com/neovim/neovim/commit/cb46f6e467268edf917cc3617b4c024a66b256de)

Yeah I figured that was one of the likely candidates.

**Comment by clason** [comment]
https://github.com/neovim/neovim/issues/27853 is the upstream issue.

(Note that the queries bundled in Neovim -- which differ from those here -- do not have this issue, so copying those to your config is a workaround in the meantime.)

**Comment by justinmk** [comment]
@clason is there somewhere that explains https://github.com/neovim/tree-sitter-vimdoc/commit/3089b7931809c1efd319f2d487baeb6719fdb6b5 and/or why it was also reverted?

**Comment by clason** [comment]
Nothing explains that commit, which is why I immediately reverted it. I would have force-pushed to erase it from existence if that were allowed.
