### ISSUE TITLE
`~` is not concealed when the line is below `============`

### ISSUE THREAD

**Issue by zeertzjq** [neovim/tree-sitter-vimdoc#135]
For example, in `:h ada.vim`, there is the following heading:
```
==============================================================================
1. Syntax Highlighting ~
```
The tilde here should be concealed, but it isn't.

**Comment by clason** [comment]
No, it shouldn't. This is an H1 heading, so the tilde (which denotes a H4 heading) is wrong and should be removed. See the Readme.
