### ISSUE TITLE
Easier/cleaner way to write tree-sitter grammar

### ISSUE THREAD

**Issue by mingodad** [neovim/tree-sitter-vimdoc#136]
Here https://mingodad.github.io/lua-wasm-playground/ there is an easier/cleaner way to write tree-sitter grammars like `vimdoc` (select `Tree-sitter-ebnf-generator-VimDoc` from `Examples` then click `Run` to see a full commented out `grammar.js` from the `EBNF` variant describng the grammar in `
Input Text (arg[1])`).

I hope it can be helpful !

**Comment by justinmk** [comment]
"easier/cleaner" meaning one can start with an EBNF grammar instead of editing grammar.js directly? Good to know, thanks.

**Comment by clason** [comment]
Thank you, but writing grammars is a craft, not a science. In fact, blindly converting an EBNF is usually [a bad idea](https://github.com/github/semantic/blob/3baf0b47ff2117a4724771687d458151ce2b92a7/docs/grammar-development-guide.md).

(PSA: I hope you're not going to open such an "issue" at every parser repo; this would count as spam.)

**Comment by mingodad** [comment]
I guess that none of you looked at it before reply !
Am I right ?

**Comment by justinmk** [comment]
I did look at it. You gave no explanation and I made my best guess as to what you mean.

**Comment by mingodad** [comment]
Thank you !
