### ISSUE TITLE
Inline code highlighting has issues

### ISSUE THREAD

**Issue by echasnovski** [neovim/tree-sitter-vimdoc#17]
There are multiple issues of recognizing inline code blocks. It usually works fine when backticks surround single word consisting from letters. Other than that, not so much.

Text:
```
`inline code with s`
`inline code with spaces`
`require('')`
`require('mod')`
`{}`
```

Current behavior with tree-sitter:
![screenshot_2022-09-26_15:46:20](https://user-images.githubusercontent.com/24854248/192280791-8673aa27-fb3b-4252-ac9c-aa7d893215e5.png)

Current behavior without tree-sitter:
![screenshot_2022-09-26_15:46:35](https://user-images.githubusercontent.com/24854248/192280816-9e8593a2-f63d-45f9-9483-6ed1f731c48e.png)

**Comment by justinmk** [comment]
should be fixed by https://github.com/vigoux/tree-sitter-vimdoc/pull/16
