### ISSUE TITLE
Hot-links are not recognized inside parenthesis

### ISSUE THREAD

**Issue by echasnovski** [neovim/tree-sitter-vimdoc#18]
Text:

```
(|aaa|) |bbb| ccc |ddd|
```

Current behavior with tree-sitter:
![screenshot_2022-09-26_16:27:18](https://user-images.githubusercontent.com/24854248/192289318-aee6425e-25eb-4ec5-8051-6cfa1981a8e3.png)

Behavior without tree-sitter:
![screenshot_2022-09-26_16:27:25](https://user-images.githubusercontent.com/24854248/192289332-6df424c7-9581-4bfa-8cfc-23c0c38a9713.png)

**Comment by justinmk** [comment]
should be fixed by https://github.com/vigoux/tree-sitter-vimdoc/pull/16

**Comment by justinmk** [comment]
> should be fixed by #16 

Actually not fixed by that PR. Will revisit in a future PR.
