### ISSUE TITLE
embedded languages in codeblocks

### ISSUE THREAD

**Issue by clason** [neovim/tree-sitter-vimdoc#2]
This is a moonshot, but would it be possible (at least in principle) to detect the language of a `code_block`? In contrast to Markdown, Vimdoc doesn't use language markers, so it's nigh impossible to set up proper injections for them. At least being able to distinguish Lua/Vimscript/Other (the last highlighted as plain string) would be great.

**Comment by clason** [comment]
Proposal from #16:

Support `lua>` and `vim>` as injected code-block markers and add these to https://github.com/neovim/neovim/blob/cfdc93e8ac3e6c1577f1582c4b9546c118aa7987/runtime/syntax/help.vim#L18

Then we can use these markers in our help files and users on legacy syntax won't see a difference while tree-sitter can highlight them accordingly.

**Comment by clason** [comment]
(or `>lua`, to have some parallel with Markdown syntax?)

**Comment by justinmk** [comment]
I lean towards keep the `>` as the last thing on the line, to avoid forking vimdoc syntax where possible (gracefully degrades).

**Comment by clason** [comment]
I think we want to add this to the syntax file anyway, to conceal the language annotation?

**Comment by clason** [comment]
Related (since I just noticed this in the README): `line-modeline` could inject the `viml` language.

**Comment by justinmk** [comment]
That might be too presumptuous, unless you mean to highlight the modeline itself (which normally should be discarded, or at least treated as noise)!

**Comment by clason** [comment]
> I lean towards keep the `>` as the last thing on the line, to avoid forking vimdoc syntax where possible (gracefully degrades).

This will make it harder to match the `lua` before it, though, as you get a conflict with the (higher precedence) `word` rule for normal text.
