### ISSUE TITLE
Conceal eats adjacent whitespace

### ISSUE THREAD

**Issue by clason** [neovim/tree-sitter-vimdoc#23]
With the new grammar and queries, open any help file (say, `:h api.txt`) and look at option or tag links: the concealed markers will include all adjacent whitespace. E.g., 
```
API Usage                                               *api-rpc* *RPC* *rpc*
```
becomes
```
API Usageapi-rpcRPCrpc
```
instead of 
```
API Usage                                               api-rpc RPC rpc
```
(This was not the case with the old parser version.)

**Comment by justinmk** [comment]
hopefully will be addressed when `#trim!` is upstreamed. `offset!` also is worth noting.

https://github.com/nvim-treesitter/nvim-treesitter/pull/2850

**Comment by bb010g** [comment]
@justinmk For `#trim!` to address this, would it need to not just trim empty lines, but also whitespace from the beginning & end of (all lines in the) region?

**Comment by justinmk** [comment]
proposed workaround: https://github.com/neovim/tree-sitter-vimdoc/pull/28

**Comment by bb010g** [comment]
`metadata[capture_id].range` isn't working like I'd expect on v0.8.0, at least given the `#offset!` examples I've seen. Here's some debug output from nvim-treesitter-playground using this in `highlights.scm` (all other `(#set! conceal "")` directives commented out):
```scm
(tag
  text: (_) @label)
(tag
  "*" @conceal (#set! conceal "")
  (#match? @conceal "^\\*$")
  text: (_))
(tag
  "*" @conceal.left (#set! conceal "")
  (#offset! @conceal.left 0 0 0 -2)
  (#match? @conceal.left "^\\s+\\*$")
  text: (_))
```
![Screen Shot 2022-10-05 at 09 11 38](https://user-images.githubusercontent.com/340132/194109615-8ef2cd9f-65eb-4279-b6fe-a48f0c73a1ac.png)
You can see that the modified range for the `"*"` anonymous node should cause all but ` *` (column range 49–51) to be concealed, but the whole node range is still concealed.

I attempted to do this without match, but there seems to be some interesting behavior with sibling ordering & anonymous nodes:
```scm
(tag
  text: (_) @label)
(tag
  text: (_)
  "*" @conceal.right (#set! conceal "")
) ; @mytest
; (tag
;   "*" @conceal (#set! conceal "")
;   (#match? @conceal "^\\*$")
;   text: (_)
; )
(tag
  "*" @conceal.left (#set! conceal "")
  ; (#offset! @conceal.left 0 0 0 -2)
  ; (#match? @conceal.left "^\\s+\\*$")
  text: (_)
)
```
![Screen Shot 2022-10-05 at 09 20 04](https://user-images.githubusercontent.com/340132/194111066-7901a385-4ea8-4192-9305-32c237719b98.png)
`@conceal.right` is properly applied only after a sibling `text: (_)`, but `@conceal.left` applies to both.

Also, for some bonus fun, if I uncomment that `; @mytest` capture on the pattern containing `@conceal.right`:
![Screen Shot 2022-10-05 at 09 22 59](https://user-images.githubusercontent.com/340132/194111561-7a1ee0e3-b18b-49f8-a1c7-f4dfa84133c1.png)
`@mytest` is now a capture that has `metadata.conceal` set! This feels pretty wrong and I'm worried it's a tree-sitter problem.

**Comment by clason** [comment]
@vigoux

**Comment by Bekaboo** [comment]
Also have this bug.

**Comment by numToStr** [comment]
Some cases are still not fixed. For example, Whitespace is still getting trimmed when you only have tags on a line like

```help
							*:setl* *:setlocal*
```

**Comment by justinmk** [comment]
Yes, seems like whitespace is included in the first node of a line. Not sure why.

**Comment by clason** [comment]
Also happens with links; see, e.g., `api.txt`, line 1547f (and many other places).

**Comment by justinmk** [comment]
Links that are the first node in the line..?

**Comment by clason** [comment]
Yes.

**Comment by clason** [comment]
This actually happens for all nodes as far as I can see: check line 22 of  `api.txt` with `hi link @text.uri Underlined` -- the underline extends to the beginning of the line.

**Comment by justinmk** [comment]
Even with current HEAD (after https://github.com/neovim/tree-sitter-vimdoc/commit/31fcaca76b4b7672d62ef7af7ae81fa15696bab1 ) ? Is the issue fixed with that?

**Comment by clason** [comment]
Is that in core?

**Comment by justinmk** [comment]
not yet

**Comment by clason** [comment]
Ah, OK. Want me to bump the parser and queries, or is there something you'd like to hold out for?

**Comment by justinmk** [comment]
No thanks, I have a PR otw
