### ISSUE TITLE
parse error for indent text block

### ISSUE THREAD

**Issue by jdhao** [neovim/tree-sitter-vimdoc#30]
The display [here](https://neovim.io/doc/user/usr_25.html#_virtual-replace-mode) is not right compared to builtin help file.
Maybe the text block should be rendered as code blocks.

**Comment by justinmk** [comment]
> Maybe the text block should be rendered as code blocks.

Definitely would be great to have block indentation indicated by the parse tree https://github.com/neovim/tree-sitter-vimdoc/issues/20

Meanwhile, most pages are rendered in fixed (preformatted) layout, like a codeblock. There is some other bug happening at https://neovim.io/doc/user/usr_25.html#_virtual-replace-mode

Thanks for reporting!
