### ISSUE TITLE
parse error: syntax.txt 

### ISSUE THREAD

**Issue by Trard** [neovim/tree-sitter-vimdoc#56]
Found `tree-sitter-vimdoc` parse error at: https://neovim.io/doc/user/syntax.html

Context:

```
	a number instead of a color name.

	Note that for 16 color ansi style terminals (including xterms), the
	numbers in the NR-8 column is used.  Here '*' means 'add 8' so that 
	Blue is 12, DarkGray is 8 etc.

	Note that for some color terminals these names may result in the wrong
```

**Comment by justinmk** [comment]
single quotes are wrong here, doc should be updated to use `"`. 

same for this line in that file:

     If you do not want complex things like '@{${"foo"}}' to be parsed:
