### ISSUE TITLE
Severe slowdown on large files

### ISSUE THREAD

**Issue by NickCondron** [neovim/tree-sitter-vimdoc#6]
## Description
Neovim lags severely when moving around large files. The lag gets worse the closer you are to the bottom of the file.
## To reproduce
`:h netrw` (4418 lines)
`G`
Observe slowdown with normal commands or simply holding `k`

**Comment by vigoux** [comment]
So the slowdown may be caused by `ERROR` nodes in the file.
I'll try to find out what happened and report it here!

**Comment by clason** [comment]
There were some improvements in https://github.com/tree-sitter/tree-sitter recently regarding `ERROR` handling -- you could try building Neovim against the latest tree-sitter commit (e.g., via `.scripts/bump-deps.sh --dep=tree-sitter --HEAD`) and see if that makes a difference?

**Comment by NickCondron** [comment]
> There were some improvements in https://github.com/tree-sitter/tree-sitter recently regarding `ERROR` handling -- you could try building Neovim against the latest tree-sitter commit (e.g., via `.scripts/bump-deps.sh --dep=tree-sitter --HEAD`) and see if that makes a difference?

I tested this and it did not fix the issue.

**Comment by vigoux** [comment]
Looking into it, there is indeed some `ERRORS` in the file. I'll try to fix them when I have time.

**Comment by justinmk** [comment]
seems fixed now. Please test with latest version and say exactly the steps you took
