### ISSUE TITLE
Tags with a dot "." beforehand isn't handled correctly

### ISSUE THREAD

**Issue by dundargoc** [neovim/tree-sitter-vimdoc#66]
The following doesn't conceal "|": `vim.api.|nvim_get_keymap()|`

**Comment by clason** [comment]
Workaround: use backticks for the first part:
```
`vim.api.`|nvim_get_keymap()|
```

**Comment by justinmk** [comment]
tangentially, I would discourage this kind of thing in help files. `|nvim_get_keymap()|` should be enough, it's noisy to spell out everywhere how to use things from Lua/Vimscript/this/that.

**Comment by clason** [comment]
(Just for the record, in case others read this: The context for this issue was the Lua guide, where "how to use things from Lua" was the whole point.)

**Comment by justinmk** [comment]
Backticks (codespan) are the escape-hatch in 99% of cases.

Marking this as wontfix because the parser cannot know if a `|` in the middle of an unbroken token is a tag or some other random vimdoc text.
