### ISSUE TITLE
Odd highlighting for `local-additions`

### ISSUE THREAD

**Issue by qubidt** [neovim/tree-sitter-vimdoc#7]
Some odd highlighting when looking at `help.txt`'s `local-additions` section

w/o TreeSitter |  w/ TreeSitter
:-----:|:-------:
![image](https://user-images.githubusercontent.com/6306455/178800952-dd4752b3-bfd6-4c82-8de3-24e5b1b014bc.png) | ![image](https://user-images.githubusercontent.com/6306455/178798285-a1990443-4c6e-4b82-a813-999d3a4a486a.png)

text:

```help
LOCAL ADDITIONS:				*local-additions*
|nvim-treesitter|  Treesitter configurations and abstraction layer for Neovim.
|packer.txt|                      A use-package inspired Neovim plugin manager
|matchit.txt|	Extended "%" matching

```

notice the `h` in `matchit.txt` is concealed

**Comment by vigoux** [comment]
So it seems that the error actually comes from line 24 in this file, where a single quote `'` is opened but never closed, thus confusing the parser.

I'll try to see what I can do.

**Comment by vigoux** [comment]
So I have pushed a workaround in 1de3ea0741da399e43035a5da1b821ae7668a29f.

The idea is that, normally, the parser should now create an `ERROR` node instead of failing silently in this situation. The proper fix I fear is not that easy, and involves some weird tricks.
