### ISSUE TITLE
Ydckogedvhdcnj

### ISSUE THREAD

**Issue by dimonzblack** [neovim/tree-sitter-vimdoc#83]
Found `tree-sitter-vimdoc` parse error at: https://neovim.io/doc/user/tagsrch.html

Context:

```
    no		yes	no    on  write current file, read other file, goto
				  tag
    no		yes	no   off  fail
-----------------------------------------------------------------------------

- If the tag is in the current file, the command will always work.
- If the tag is in another file and the current file was not changed, the
  other file will be made the current file and read into the buffer.
```

**Comment by clason** [comment]
I appreciate you reporting these parsing issues, but can you at least leave the title intact and not vandalize them with random text? This makes it actively harder to fix these issues, to the point where I'm starting to prefer you _not_ opening new issues.
