### ISSUE TITLE
Missing newline in pattern docs

### ISSUE THREAD

**Issue by durka** [neovim/tree-sitter-vimdoc#96]
In the [Pattern docs, Magic section](https://neovim.io/doc/user/pattern.html#%2Fmagic), there is a table. A newline is missing before the tilde row, breaking the layout.

![image](https://user-images.githubusercontent.com/47007/222882172-53dcfdea-f8f7-4cce-98e9-c2faca28391f.png)

**Comment by justinmk** [comment]
This might be due to the leading `*` on the previous line. https://github.com/neovim/tree-sitter-vimdoc/pull/97 should resolve this.
