### ISSUE TITLE
Vimdoc parser breaks down around LOCAL ADDITIONS in the help section

### ISSUE THREAD

**Issue by dundargoc** [neovim/tree-sitter-vimdoc#99]
The text changes based on installed plugins, so it's not always apparent. Minimal reproduction:

```
LOCAL ADDITIONS:				*local-additions*
|lazy.nvim.txt|         For Neovim >= 0.8.0         Last change: 2023 March 07
|nvim-treesitter|  Treesitter configurations and abstraction layer for Neovim.
|matchit.txt|	Extended "%" matching
```

**Comment by clason** [comment]
screenshots shows this better:

<img width="569" alt="Screenshot 2023-03-11 at 22 38 56" src="https://user-images.githubusercontent.com/2361214/224512616-c87cb016-b0d2-4e7c-9cb6-7b08228ebb89.png">

**Comment by justinmk** [comment]
@clason  are you seeing that on your system? When I use `:InspectTree` on the provided text the parse tree looks perfect (`NVIM v0.9.0-dev-1163+g4385f8a7430f`):

```
(block) ; [1:1 - 5]
 (line) ; [1:1 - 1]
  (word) ; [1:1 - 6:0]
  (word) ; [1:7 - 16:0]
  (word) ; [1:16 - 17:0]
  (tag) ; [1:21 - 38:0]
   text: (word) ; [1:22 - 37:0]
 (line) ; [2:1 - 1:2]
  (taglink) ; [2:1 - 16:1]
   text: (word) ; [2:2 - 15:1]
  (word) ; [2:25 - 28:1]
  (word) ; [2:29 - 35:1]
  (word) ; [2:36 - 37:1]
  (word) ; [2:37 - 38:1]
  (word) ; [2:39 - 44:1]
  (word) ; [2:53 - 57:1]
  (word) ; [2:58 - 65:1]
  (word) ; [2:66 - 70:1]
  (word) ; [2:71 - 76:1]
  (word) ; [2:77 - 79:1]
 (line) ; [3:1 - 1:3]
  (taglink) ; [3:1 - 18:2]
   text: (word) ; [3:2 - 17:2]
  (word) ; [3:20 - 30:2]
  (word) ; [3:31 - 45:2]
  (word) ; [3:46 - 49:2]
  (word) ; [3:50 - 61:2]
  (word) ; [3:62 - 67:2]
  (word) ; [3:68 - 71:2]
  (word) ; [3:72 - 79:2]
 (line) ; [4:1 - 1:4]
  (taglink) ; [4:1 - 14:3]
   text: (word) ; [4:2 - 13:3]
  (word) ; [4:15 - 23:3]
  (word) ; [4:24 - 27:3]
  (word) ; [4:28 - 36:3]
```

**Comment by justinmk** [comment]
Could `nvim-treesitter` be interfering? I don't have it enabled.

**Comment by dundargoc** [comment]
n=1 for the culprit being `nvim-treesitter`, I can recreate the problem with nvim-treesitter but not with the builtin parser.

**Comment by clason** [comment]
I'm actually seeing this on my system, yes, and it's without nvim-treesitter. I'll try to paste the tree, but I'm getting an error traversing it right now (probably an unrelated regression from recent treesitter refactors):
```
Error detected while processing CursorMoved Autocommands for "<buffer=3>":
Error executing lua callback: /usr/local/share/nvim/runtime/lua/vim/treesitter.lua:554: Invalid 'col': out of
range
stack traceback:
        [C]: in function 'nvim_buf_set_extmark'
        /usr/local/share/nvim/runtime/lua/vim/treesitter.lua:554: in function </usr/local/share/nvim/runtime/l
ua/vim/treesitter.lua:550>
```

**Comment by clason** [comment]
(Weird, I never noticed that the row and column are flipped in the node range end, compared to the start.)

**Comment by clason** [comment]
Update: copying the generated file into a fresh buffer works fine, so this may be a race condition? (Disabling and re-enabling treesitter doesn't make a difference, though.)

**Comment by clason** [comment]
But there _is_ one minor issue: the `LOCAL ADDITIONS:` are not parsed as a column heading due to the trailing colon ;)
